Section "ServerLayout"
    Identifier "AVELL"
    Screen 0 "eDP1-S" 0 0
    Screen 1 "HDMI1-S" RightOf "eDP1-S"
EndSection

Section "Extensions"
    Option      "DPMS" "Disable"
EndSection

Section "OutputClass"
    Identifier "iGPU"
    MatchDriver "i965"
    Driver "intel"
    Option "DRI" "2"
    Option "TearFree" "on"
    Option "AccelMethod" "uxa"
    Option "TripleBuffer" "true"
EndSection

#Section "OutputClass"
#    Identifier "iGPU"
#    MatchDriver "i965"
#    Driver "modesetting"
#EndSection

Section "OutputClass"
    Identifier "dGPU"
    MatchDriver "nvidia-drm"
    Driver "nvidia"
    Option "AllowEmptyInitialConfiguration"

    #Option "Coolbits" "28" #"31"
    #Option "ProbeAllGpus" "off"
    #Option "AllowSHMPixmaps" "off"
    #Option "Interactive" "off"
    #Option "InbandStereoSignaling" "on"
    #Option "UseSysmemPixmapAccel" "on"
    #Option "ThermalConfigurationCheck" "off"
    #Option "NoPowerConnectorCheck" "off"
    #Option "ConnectToAcpid" "off"
    #Option "MetaModes" "nvidia-auto-select +0+0 {ForceCompositionPipeline=On, ForceFullCompositionPipeline=On}"

    Option "ForceFullCompositionPipeline" "on"
    Option "RegistryDwords" "PowerMizerEnable=0x1; PerfLevelSrc=0x3322; PowerMizerDefault=0x1; PowerMizerDefaultAC=0x1"
    Option "AllowIndirectGLXProtocol" "off"
    Option "TripleBuffer" "on"
    
    Option "PrimaryGPU" "no"
    ModulePath "/usr/lib/nvidia/xorg"
    ModulePath "/usr/lib/xorg/modules"
EndSection


Section "Monitor"
    Identifier "eDP1"
    Option "Primary" "on"
    Option "PreferredMode" "1920x1080_60.00"
    Option "DPMS" "off"
EndSection

Section "Monitor"
    Identifier "HDMI1"
    Option "RightOf" "eDP1"
    Option "PreferredMode" "1920x1080_60.0"
    Option "DPMS" "off"
EndSection

Section "Screen"
    Identifier "eDP1-S"
    Monitor "eDP1"
    Device "iGPU"
Endsection

Section "Screen"
    Identifier "HDMI1-S"
    Monitor "HDMI1"
    Device "iGPU"
Endsection
