Section "ServerLayout"
    Identifier "AVELL"
    Screen 0 "eDP1-S" 0 0
    Screen 1 "HDMI1-S" RightOf "eDP1-S"
EndSection

Section "Extensions"
    Option      "DPMS" "Disable"
EndSection

#Section "OutputClass"
#    Identifier "iGPU"
#    MatchDriver "i965"
#    Driver "modesetting"
#    Option "TearFree" "true"
#EndSection

Section "OutputClass"
    Identifier "iGPU"
    MatchDriver "i915"
    Driver "modesetting"
EndSection

Section "OutputClass"
    Identifier "dGPU"
    MatchDriver "nvidia-drm"
    Driver "nvidia"
    Option "AllowEmptyInitialConfiguration"
    #Option "PrimaryGPU" "yes"
    ModulePath "/usr/lib/nvidia/xorg"
    ModulePath "/usr/lib/xorg/modules"
EndSection


Section "Monitor"
    Identifier "eDP1"
    Option "Primary" "true"
    Option "PreferredMode" "1920x1080_60.00"
    Option "DPMS" "false"
EndSection

Section "Monitor"
    Identifier "HDMI1"
    Option "RightOf" "eDP1"
    Option "PreferredMode" "1920x1080_60.0"
    Option "DPMS" "false"
EndSection

Section "Screen"
    Identifier "eDP1-S"
    Monitor "eDP1"
    Device "iGPU"
Endsection

Section "Screen"
    Identifier "HDMI1-S"
    Monitor "HDMI1"
    Device "iGPU"
Endsection
