#!/bin/bash
xrandr --output HDMI1 --mode 1920x1080 --right-of eDP1 --mode 1920x1080 &
xset s off &
xset -dpms &
numlockx on &
xinput --set-prop 14 "Device Enabled" 0 &
mpd ~/.config/mpd/mpd.conf &
feh --no-fehbg --bg-fill ~/Pictures/Wallpapers/Cool-Abstract-4K-1920x1080.jpg --bg-fill ~/Pictures/Wallpapers/Cool-Abstract-4K-1920x1080.jpg &
~/.config/polybar/launch.sh --blocks &
