#!/bin/bash

dbus-update-activation-environment DISPLAY XDG_CURRENT_DESKTOP=KDE
dbus-update-activation-environment --systemd DISPLAY XDG_CURRENT_DESKTOP

systemctl --user stop plasma-kscreen.service
xrandr --output DP-4 --primary --mode 3440x1440 --scale 1x1 --dpi 96 --rate 165.00

xset r rate 300 50 &
xset s off &
xset -dpms &

/usr/lib/polkit-kde-authentication-agent-1 &
/usr/lib/pam_kwallet_init &
kwalletd6 &

picom &
xwallpaper --zoom ~/.config/background/katana-anime-girl-neon-4k-9s-3440x1440.jpg &
numlockx on
dunst --config ~/.config/dunst/dunstrc &

XDG_MENU_PREFIX=arch- kbuildsycoca6
