#!/bin/bash

# NVIDIA
xrandr --output eDP-1-1  --mode 1920x1080
xrandr --output HDMI-1-1 --mode 1920x1080
xrandr --output eDP-1-1 --left-of HDMI-1-1

#xrandr --output HDMI-1 --mode 1920x1080 --right-of eDP-1 --mode 1920x1080
xinput --set-prop 13 "Device Enabled" 0
xset s off
#xset -dpms
numlockx on
#dwmblocks &
nitrogen --restore &
#xcompmgr &
#mpd ~/.config/mpd/mpd.conf
picom --experimental-backends &
exec slstatus &
#wallpaper-wrap &
